import type { Product } from "./types";

export const SEED_PRODUCTS: Product[] = [
  {
    id: "harbor-police-station",
    name: "Harbor Police Station",
    description:
      "A waterfront precinct with a dock, patrol boat, and a three-level station packed with everyday city detail. Build the jetty, lock-up, and rooftop lookout, then stage rescues along the harbor edge.",
    price: 89000,
    salePrice: null,
    images: [],
    category: "city",
    ageRange: "8+",
    pieceCount: 845,
    stock: 18,
    isNew: true,
    isBestSeller: false,
    isSale: false,
    soldCount: 24,
    createdAt: "2026-08-12T09:00:00.000Z",
  },
  {
    id: "downtown-fire-station",
    name: "Downtown Fire Station",
    description:
      "A brick-and-steel firehouse with a sliding pole, two-bay garage, and a ladder truck ready for night calls. The roof opens for a command deck, and the street scene includes a hydrant and alarm box.",
    price: 125000,
    salePrice: null,
    images: [],
    category: "city",
    ageRange: "9+",
    pieceCount: 1024,
    stock: 11,
    isNew: false,
    isBestSeller: true,
    isSale: false,
    soldCount: 86,
    createdAt: "2026-05-03T09:00:00.000Z",
  },
  {
    id: "mountain-cargo-train",
    name: "Mountain Cargo Train",
    description:
      "A long-haul freight set with a locomotive, three cargo wagons, and a hillside depot. Load timber, crates, and fuel tanks, then run the line through a switch track and timber trestle.",
    price: 198000,
    salePrice: null,
    images: [],
    category: "city",
    ageRange: "10+",
    pieceCount: 1560,
    stock: 7,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 31,
    createdAt: "2026-03-18T09:00:00.000Z",
  },
  {
    id: "offroad-rally-truck",
    name: "Off-Road Rally Truck",
    description:
      "A high-clearance Technic truck with working suspension, a detailed cockpit, and chunky all-terrain tires. Steer through the chassis geometry and study the exposed gearbox as you build.",
    price: 245000,
    salePrice: null,
    images: [],
    category: "technic",
    ageRange: "11+",
    pieceCount: 2192,
    stock: 9,
    isNew: false,
    isBestSeller: true,
    isSale: false,
    soldCount: 64,
    createdAt: "2026-04-22T09:00:00.000Z",
  },
  {
    id: "twin-rotor-rescue",
    name: "Twin-Rotor Rescue Helicopter",
    description:
      "A mechanical rescue helicopter with linked rotors, a sliding cargo door, and a winch. The build focuses on gear meshing and a sturdy tail boom that stays true under the spinning blades.",
    price: 156000,
    salePrice: null,
    images: [],
    category: "technic",
    ageRange: "10+",
    pieceCount: 1045,
    stock: 14,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 29,
    createdAt: "2026-06-09T09:00:00.000Z",
  },
  {
    id: "forest-treehouse",
    name: "Forest Treehouse",
    description:
      "A three-way Creator hideaway nested in a canopy of greens and timber tones. Rebuild it as a treetop cabin, a lakeside lookout, or a woodland workshop with lanterns and hanging bridges.",
    price: 289000,
    salePrice: null,
    images: [],
    category: "creator",
    ageRange: "12+",
    pieceCount: 3036,
    stock: 5,
    isNew: true,
    isBestSeller: false,
    isSale: false,
    soldCount: 19,
    createdAt: "2026-08-04T09:00:00.000Z",
  },
  {
    id: "vintage-camera",
    name: "Vintage Camera",
    description:
      "A compact Creator display model of a classic rangefinder camera, complete with a strap, flash, and a tiny photo tile. A satisfying desk-size build with clever SNOT techniques.",
    price: 48000,
    salePrice: null,
    images: [],
    category: "creator",
    ageRange: "8+",
    pieceCount: 611,
    stock: 22,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 41,
    createdAt: "2026-02-14T09:00:00.000Z",
  },
  {
    id: "heartlake-art-studio",
    name: "Heartlake Art Studio",
    description:
      "A sunlit studio with easels, a kiln corner, and a rooftop terrace for sketching. Shelves hold paints and sculptures, and the facade opens wide so the whole interior stays in play.",
    price: 72000,
    salePrice: null,
    images: [],
    category: "friends",
    ageRange: "8+",
    pieceCount: 843,
    stock: 16,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 33,
    createdAt: "2026-07-01T09:00:00.000Z",
  },
  {
    id: "beach-house-retreat",
    name: "Beach House Retreat",
    description:
      "A two-story coastal home with sliding glass, a hammock deck, and a sandy garden path. Build the kitchen nook, loft bedroom, and a small dock for sunset evenings by the water.",
    price: 118000,
    salePrice: 98000,
    images: [],
    category: "friends",
    ageRange: "9+",
    pieceCount: 1348,
    stock: 8,
    isNew: false,
    isBestSeller: false,
    isSale: true,
    soldCount: 47,
    createdAt: "2026-01-20T09:00:00.000Z",
  },
  {
    id: "grand-prix-racer",
    name: "Grand Prix Racer",
    description:
      "A low, aggressive open-wheel racer with a halo cockpit, slick tires, and sponsor-style color blocking. Display it on the included pit stand or roll it along a desk raceline.",
    price: 65000,
    salePrice: null,
    images: [],
    category: "cars",
    ageRange: "8+",
    pieceCount: 670,
    stock: 20,
    isNew: false,
    isBestSeller: true,
    isSale: false,
    soldCount: 112,
    createdAt: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "midnight-gt-coupe",
    name: "Midnight GT Coupe",
    description:
      "A midnight-blue grand tourer with working doors, a detailed cabin, and a wide rear stance. The build rewards patience with layered bodywork and a garage plaque for the finished model.",
    price: 175000,
    salePrice: null,
    images: [],
    category: "cars",
    ageRange: "10+",
    pieceCount: 1458,
    stock: 6,
    isNew: true,
    isBestSeller: false,
    isSale: false,
    soldCount: 18,
    createdAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "neon-night-drifter",
    name: "Neon Night Drifter",
    description:
      "A street-tuned coupe in neon coral and ink black, built for night circuits. Includes a low splitter, light-bar roof, and a compact display base with a city-grid tile.",
    price: 110000,
    salePrice: null,
    images: [],
    category: "cars",
    ageRange: "9+",
    pieceCount: 892,
    stock: 12,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 38,
    createdAt: "2026-06-21T09:00:00.000Z",
  },
  {
    id: "skyline-landmark-tower",
    name: "Skyline Landmark Tower",
    description:
      "A refined architecture model of a riverfront tower, scaled for a shelf. Layered tan, stone, and glass bricks capture setbacks, terraces, and a quiet plaza at the base.",
    price: 215000,
    salePrice: null,
    images: [],
    category: "architecture",
    ageRange: "16+",
    pieceCount: 2101,
    stock: 4,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 22,
    createdAt: "2026-03-08T09:00:00.000Z",
  },
  {
    id: "riverside-pagoda",
    name: "Riverside Pagoda",
    description:
      "A calm, stacked-roof pagoda beside a brick river walk. Build the terraces, lanterns, and surrounding trees as a display piece with a grounded, architectural silhouette.",
    price: 95000,
    salePrice: null,
    images: [],
    category: "architecture",
    ageRange: "14+",
    pieceCount: 980,
    stock: 10,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 27,
    createdAt: "2026-05-27T09:00:00.000Z",
  },
  {
    id: "lunar-research-base",
    name: "Lunar Research Base",
    description:
      "A modular moon lab with living quarters, a greenhouse dome, and a rover garage. Connect the airlock corridors and stage EVAs on the cratered display plate.",
    price: 188000,
    salePrice: null,
    images: [],
    category: "space",
    ageRange: "10+",
    pieceCount: 1684,
    stock: 9,
    isNew: true,
    isBestSeller: false,
    isSale: false,
    soldCount: 21,
    createdAt: "2026-08-08T09:00:00.000Z",
  },
  {
    id: "deep-space-explorer",
    name: "Deep Space Explorer",
    description:
      "A compact explorer ship with rotating sensor arrays and a split hull that reveals the crew deck. Built for shelf display with a translucent stand that suggests zero gravity.",
    price: 78000,
    salePrice: 62000,
    images: [],
    category: "space",
    ageRange: "8+",
    pieceCount: 754,
    stock: 13,
    isNew: false,
    isBestSeller: false,
    isSale: true,
    soldCount: 55,
    createdAt: "2026-02-02T09:00:00.000Z",
  },
  {
    id: "orbital-shuttle",
    name: "Orbital Shuttle",
    description:
      "A large shuttle orbiter with opening payload bay, landing gear, and a service tower. The build is a statement piece — long, white, and carefully paneled.",
    price: 320000,
    salePrice: null,
    images: [],
    category: "space",
    ageRange: "12+",
    pieceCount: 2334,
    stock: 3,
    isNew: false,
    isBestSeller: true,
    isSale: false,
    soldCount: 48,
    createdAt: "2026-01-11T09:00:00.000Z",
  },
  {
    id: "jungle-wildlife-sanctuary",
    name: "Jungle Wildlife Sanctuary",
    description:
      "A raised canopy walk and ranger station surrounded by dense foliage. Build habitats for big cats, birds, and river creatures, with a hidden cave behind the waterfall.",
    price: 132000,
    salePrice: null,
    images: [],
    category: "animals",
    ageRange: "9+",
    pieceCount: 1212,
    stock: 11,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 36,
    createdAt: "2026-07-16T09:00:00.000Z",
  },
  {
    id: "coral-reef-adventure",
    name: "Coral Reef Adventure",
    description:
      "A vivid reef diorama with a glass-bottom boat, diving platform, and schools of bright sea life. The baseplate curves into a drop-off packed with coral textures.",
    price: 52000,
    salePrice: null,
    images: [],
    category: "animals",
    ageRange: "7+",
    pieceCount: 562,
    stock: 17,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 44,
    createdAt: "2026-04-30T09:00:00.000Z",
  },
  {
    id: "first-build-town",
    name: "First Build Town",
    description:
      "A cheerful starter town with large, easy-to-handle bricks, a bakery, a garage, and a park. Designed for first builders who want a complete little street in one box.",
    price: 28000,
    salePrice: null,
    images: [],
    category: "kids",
    ageRange: "4+",
    pieceCount: 215,
    stock: 28,
    isNew: false,
    isBestSeller: true,
    isSale: false,
    soldCount: 140,
    createdAt: "2026-03-01T09:00:00.000Z",
  },
  {
    id: "rainbow-brick-bucket",
    name: "Rainbow Brick Bucket",
    description:
      "A generous open-play bucket of bright bricks, wheels, windows, and eyes. No instructions required — just dump, sort, and invent. Ideal as a gift or a workshop refill.",
    price: 35000,
    salePrice: null,
    images: [],
    category: "kids",
    ageRange: "4+",
    pieceCount: 450,
    stock: 34,
    isNew: false,
    isBestSeller: false,
    isSale: false,
    soldCount: 97,
    createdAt: "2026-06-02T09:00:00.000Z",
  },
  {
    id: "classic-mix-workshop",
    name: "Classic Mix Workshop",
    description:
      "A curated mixed-brick workshop box with plates, slopes, tiles, and a tray of extras. Perfect for custom builds, repairs, and expanding any collection on the workbench.",
    price: 85000,
    salePrice: 69000,
    images: [],
    category: "other",
    ageRange: "6+",
    pieceCount: 1500,
    stock: 15,
    isNew: false,
    isBestSeller: false,
    isSale: true,
    soldCount: 58,
    createdAt: "2026-02-22T09:00:00.000Z",
  },
];
